
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";
import Navbar from "@/components/navbar/Navbar";
import { BlogProvider } from "@/Context/BlogContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page Of Blog-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url(&apos;https://fonts.googleapis.com/css2?family=Pacifico&display=swap&apos;);
        </style>
      </head>
      <body
        className={`  bg-gray-200 ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen `}
      >
        <AuthProvider>
          <BlogProvider>
            <div>
              <Navbar />
              {children}
            </div>
          </BlogProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
